name: Cypress Tests

on: 
  schedule:
    - cron: '0 7 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress smoke
        uses: cypress-io/github-action@v6
        with:
          command: npm run cucumber-test
          build: npx cypress info
          browser: chrome
        
