name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress smoke
        uses: cypress-io/github-action@v6
        with:
          command: npm run smoke:allure
          build: npx cypress info
          browser: chrome
          java-version: "11"
        
