name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      
      # Install NPM dependencies
      - name: Set up npm package
        run: npm install
        
      - name: Run smoke suite
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          command: npm run smoke:test
          browser: chrome
          config-file: ./cypress.config.js
          
      - name: Copy test execution videos, screenshots and reports
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
          cp -a allure-report/. public
          cp -r allure-results public/allure-results
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public