name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      
      # Install NPM dependencies
      - name: Set up npm package
        run: npm install
        
      - name: Run smoke suite
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:execution-allure
          build: npx cypress info
          browser: chrome
          config-file: ./cypress.config.js           
      
      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: allure
          path: allure
          
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: allure-results
          allure_report: allure-report
          gh_pages: allure
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: allure
          publish_dir: allure-history
