name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: setup Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
      
      # Install NPM dependencies
      - name: Set up npm package
        run: npm install
        
      - name: Run smoke suite
        uses: cypress-io/github-action@v6
        with:
          command: npm run smoke:test
          build: npx cypress info
          browser: chrome
          config-file: ./cypress.config.js
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report
