name: Cypress scheduled Tests

on:
  schedule:
    - cron: '32 5 * * *'

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Set up npm package
        run: npm install
        
      - name: Run smoke suite
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          command: npm run smoke:test
          browser: chrome
          config-file: ./cypress.config.js